# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9038ada8317c2a8d084caee79d86e71ae48f081b251d5f3c6e324794264ada4bf03a50a79cfff2ac593c3caefab4b97e1b496bdbab0c4b7cc619e0fa0a40aa38

test:
  secret_key_base: 81d35c15ba06bc8aefe88499299145aac98a31b008a06e5347dfccf499db03029d52b07fcc1be70d5c206a76ef2758a8a3602c7b712c2fdad696df348cebc146

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
