# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56539140406e6f12a8589203efc077686e2a5063a90bac8788c49b6f5b2d48bff227d944d7356580178c3a3da2ea0a85307f14d3d0166dc85bc742cd3ff9c73b

test:
  secret_key_base: 74102e52c90eb92972ea834bba3f7e11b62dec9b640b12a1f2e13a09b6531e7762d7981e498cd9d7adae4ab9e8c9156856c9ddabbe03714efa1a0d738c8a42b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
