# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6599b06f14dfc2d457a3ba10c6eab8f663e6bdffd092c4c15fd4ef7094a7ed532e3a7d6c83f784a53c21f7d3d6b861281b5ff4bb6f33a24c85b722c03f2cf892

test:
  secret_key_base: 1b9d2482865b381e31b908fb6e002c8bfab5da17827c3b63f40ceb2e44212ef5fa7305896f4f47d2f827c9e05416488ffb8ec12f4ca325126f86516898b834c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
