# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10dbd11d9461c327e9aba1b605a07f49a66f52ed6686ea0977353d97cc767fd837040dc0db4ddd6df0615bcf3adbe8e69bf29f286e021b4d53a208e76bd45728

test:
  secret_key_base: 829b46084bbc7991eb6cbe8b34da92732f807314740055f3849ce4e3d1b09abe1d6a08d29de1cc80a69f49d0c7e2867dd1d066e95b4eb375c3217803629c275a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
